### PR TITLE
Gov doc testing, serials format

### PR DESCRIPTION
**Pull request by kspurgin**
Conceivably sound recordings and scores could be government documents. At the very least I'd like to be able to throw that method at all records in a file and not get Missing Method errors  if there happen to be scores or sound recordings in the bunch. Added the is_govdoc? method to the public methods for sound_type and score_type. 

Got an error processing a record with LDR/06 = a and LDR/07 = i. Textual integrating resources do exist and are handled on the Continuing Resources (SER) workform, so I updated leader.rb to categorize this appropriately.

### CODE REVIEW

**Comment by kspurgin** [comment]
Yay, Git... I was trying to keep two pull requests separate because these changes were super simple and I expected non-controversial while the "keep orig blvl" changes seemed more potentially problematic. But I needed all the changes locally in my work and the way I did that ended up adding all the changes here. 

I'll cancel the other pull request. These were my comments on the "keep orig blvl" changes: 

I was using this to test enhanced_marc results for records: 

```
Dir.glob("test/data/*.mrc").each do | mrc |
  MARC::Reader.new(mrc).each do |rec|
  puts "File: #{mrc}"
  puts "Rec type: #{rec.class}"
  puts "LDR: #{rec.leader}"
  puts "Blvl: #{rec.bibliographic_level}"
  puts "\n\n"
  end
end
```

Initially I was getting results like the following, where the bibliographic_level reported back was not the BLvl from the record leader: 

```
File: test/data/ebook_coll.mrc
Rec type: MARC::BookRecord
LDR: 01787nac  2200313 a 4500
Blvl: Monograph/Item

File: test/data/ebook_part.mrc
Rec type: MARC::BookRecord
LDR: 02034caa  22003611i 4500
Blvl: Monograph/Item

File: test/data/manuscript_coll.mrc
Rec type: MARC::BookRecord
LDR: 01918ctc  2200337Ma 4500
Blvl: Monograph/Item
```

It seemed the way the new, typed records were getting created by the overrides to MARC::Reader was setting the bibliographic_level attribute at a point when the typed record's leader was still the default/blank one created at initialization.

I fixed this by adding an optional leader parameter to all the initialize methods on the *Record classes. Reader passes in the leader it just decoded when it calls the creation of a new typed record, causing bibliographic_level to be set correctly. If a Record is initialized another way or leader parameter is not passed in for some reason, default blank new Leader object is passed through by default.

I don't particularly like overriding the initialize method for *Record that way, but it's what I got to work today... 

Results after my changes: 

```
File: test/data/ebook_coll.mrc
Rec type: MARC::BookRecord
LDR: 01787nac  2200313 a 4500
Blvl: Collection

File: test/data/ebook_part.mrc
Rec type: MARC::BookRecord
LDR: 02034caa  22003611i 4500
Blvl: Monographic component part

File: test/data/manuscript_coll.mrc
Rec type: MARC::BookRecord
LDR: 01918ctc  2200337Ma 4500
Blvl: Collection
```

**Comment by rsinger** [comment]
Hi @kspurgin!  I don't have a problem with making `is_govdoc()`, public on everything for consistency.  I don't think there's actually a possible way for scores or sound recordings to be cataloged as a govdoc, though?  I mean, that's fine - it should just always return `false`, which, feels like the right behavior.

Regarding the main issue you're reporting here, do you have a representative MARC record (or, ideally, records) that trigger this issue?

My concern about passing in the LDR to circumvent the issue is that it runs counter to the intended 'convenience' of the whole project.  That is to say, I wrote this so that a developer doesn't even have to know that there's even such thing as a MARC leader in the first place ;).

All that said, it's highly possible that the entire user base of enhanced-marc is you, so I don't want to waste a ton of your time falling down a rabbit hole to find the underlying problem.  If the solution is obvious, let's fix that; if it's not immediately clear, let's just roll with your proposed change.

Sound ok?

**Comment by kspurgin** [comment]
Hi @rsinger! While the 008 definitions for Music and Mixed Materials don't have byte positions defined for 'government publication', an 006 could be added to one of these workforms that would express govdoc-ness. 

Highly unlikely/edge case-y, and I admit I didn't test what happens in this situation. The main thing on that front was being able to test is_govdoc? without errors. 

Yeah, my solution to the blvl issue felt clearly hacky and suboptimal, but I'm trying to not go down about 5 rabbit holes on the project I'm using this for, so I went ahead with what I was able to get working without taking the whole thing apart. :-) 

I'm guessing it's the blvl issue you're asking for MARC examples of? Looks like GitHub won't let me attach .mrc files, so I'm zipping some records up that could be used to test all the things I did. 

These will illustrate the blvl issue: ebook_coll, ebook_part, manuscript_coll, sound_recording_collection, sound_recording_component_part, sound_recording_subunit

The one where I ran into trouble with LDR/06 = a and LDR/07 = i was text_web_resource

[marc.zip](https://github.com/rsinger/enhanced-marc/files/1009007/marc.zip)

thanks!

**Comment by rsinger** [comment]
Ok, https://github.com/rsinger/enhanced-marc/pull/3 should fix the problem.

I'll add some tests (hopefully tomorrow) to instill a modicum of confidence in this.

Comments welcome on whether or not ripping out the lazy-loaded attributes will be any kind of performance issue for you (my hunch is that's the least of the problems, performance-wise).

**Comment by rsinger** [comment]
@kspurgin can you try out https://rubygems.org/gems/enhanced_marc/versions/0.3.1 and see if it works as expected for you?

**Comment by kspurgin** [comment]
All looks good, except I think the LDR/07 code i didn't get added to the mapping to identify a record type as SER: 

```
File: test/data/text_web_resource.mrc
Rec type: MARC::Record
LDR: 01573nai  2200373 i 4500
Blvl: Integrating resource
./test_enhanced_marc.rb:12:in `block (2 levels) in <main>': undefined method `is_govdoc?' for #<MARC::Record:0x3875cb8> (NoMethodError)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/marc-1.0.0/lib/marc/reader.rb:234:in `block in each'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/marc-1.0.0/lib/marc/reader.rb:273:in `each_raw'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/marc-1.0.0/lib/marc/reader.rb:232:in `each'
        from ./test_enhanced_marc.rb:7:in `block in <main>'
        from ./test_enhanced_marc.rb:6:in `each'
        from ./test_enhanced_marc.rb:6:in `<main>'
```

Integrating resources can definitely be govdocs, so that test shouldn't throw an error. 

In my version, I'd changed line 76 of leader.rb to: 

```
'SER' => { type: /[a]{1}/, blvl: /[bis]{1}/ },
```

thanks!

**Comment by rsinger** [comment]
Ok, that should be fixed in https://rubygems.org/gems/enhanced_marc/versions/0.3.2 - let me know!

**Comment by kspurgin** [comment]
Looks great! Thanks a bunch.

**Comment by rsinger** [comment]
:+1:

**Pull request closed without merging**
